title: The Deployment of a LoRaWAN-Based IoT Air Quality Sensor Network for Public Good
logo: /assets/img/logo.jpg
description: A University of Virginia School of Data Science research project aiming to implement a network of air quality sensors in collaboration with the local community as a means to analyze and facilitate discussion about the air we breathe.
show_downloads: true
theme: jekyll-theme-minimal
